#include <iostream>
#include <fstream>
#include "CodeGenerator.h"

using namespace std;

CodeGen::CodeGen (string filename, LexicalAnalyzer * L)
{
	cout << "CodeGen object constructed with filename: " << filename << "; and lex Obj: " << L << endl;
	lex = L;
	string cppname = filename.substr (0, filename.length()-3) + ".cpp"; 
	cpp.open (cppname.c_str());
	cpp << "// Autogenerated Scheme to C++ Code\n";
	cpp << "// File: " << cppname << "\n";
	cpp << "#include <iostream>\n";
	cpp << "#include \"Object.h\"\n";
	cpp << "using namespace std;\n\n";
	cpp.flush();
}

/********************************************************************************/
/* This function will close the cpp file.       								*/
/********************************************************************************/
CodeGen::~CodeGen ()
{
	cpp.close();
}

/********************************************************************************/
/* This function will								*/
/********************************************************************************/
void CodeGen::WriteCode (int tabs, string code)
{
	cout << "Inside WriteCode with tabs: " << tabs << "; and code: " << code << ";" << endl;
	for (int t = 0; t < tabs; t++){
		cpp << '\t';
	}
	cpp << code;
	cpp << endl;
	cpp.flush();
}
