// Autogenerated Scheme to C++ Code
// File: definer.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object xFactor ()
{
	Object __RetVal;
	__RetVal = Object("x");
	return __RetVal;
}

